### ISSUE TITLE
Attribute error.I am using MAC with python 3.6 and tensorflow installed

### ISSUE THREAD

**Issue by Sorna210** [leopard1/BiGRU-Summarization#17]
Feb 13 23:49 summarization.py[line:195] INFO Creating 1 layers of 400 units.
Traceback (most recent call last):
  File "src/summarization.py", line 241, in <module>
    tf.app.run()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 124, in run
    _sys.exit(main(argv))
  File "src/summarization.py", line 229, in main
    decode()
  File "src/summarization.py", line 196, in decode
    model = create_model(sess, True)
  File "src/summarization.py", line 75, in create_model
    dtype=dtype)
  File "/Users/twister_mn/headlinesg/tfsum/src/bigru_model.py", line 87, in __init__
    decoder_cell = tf.contrib.seq2seq.DynamicAttentionWrapper(
AttributeError: module 'tensorflow.contrib.seq2seq' has no attribute 'DynamicAttentionWrapper'

**Comment by yasersakkaf** [comment]
How were you able to solve this problem.
I am getting the same issue. Please help

**Comment by Sorna210** [comment]
use the specified version of tensorflow in the prerequisites
